In [1]:
import pandas as pd
import numpy as np
import re
import nltk
import matplotlib.pyplot as plt
import seaborn as sns
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')
from nltk.corpus import stopwords
stop_words = stopwords.words('english')
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet
from sklearn.feature_extraction.text import CountVectorizer

# notebook configurations
pd.options.display.max_colwidth = 1000

import warnings
warnings.filterwarnings("ignore")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\audre\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\audre\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\audre\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\audre\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [2]:
df = pd.read_csv("./csv_files/suicide.csv")

df["Tweet"].fillna("", inplace=True)

text = df["Tweet"]

vectorizer = CountVectorizer()

# puts the unique text words into an array 
bow_matrix = vectorizer.fit_transform(text)

# print(sorted(vectorizer.vocabulary_))

# puts the count of the word in the array for each tweet
bow_arrays = bow_matrix.toarray()

bow_arrays.shape



# print(bow_arrays)

# for i, row in enumerate(bow_arrays):
#     # Find indices where the value is greater than 0
#     indices = [index for index, value in enumerate(row) if value > 0]
#     if indices:  # Print only if there are indices greater than 0
#         print(f"Row {i}: Indices with value greater than 0 -> {indices}")







(1787, 5026)

In [3]:
df_sentiment = pd.read_csv("./csv_files/sentiment_scores.csv") 
df_sentiment.head()

compound_scores = df_sentiment["compound_scores"].values

#check if the dimensions match
if len(bow_arrays) == len(compound_scores):
    bow_arrays_with_scores = np.column_stack((bow_arrays, compound_scores))
    print(bow_arrays_with_scores)
else:
    print("Dimensions do not match. Cannot append compound scores.")


bow_arrays_with_scores.shape


[[ 0.      0.      0.     ...  0.      0.      0.    ]
 [ 0.      0.      0.     ...  0.      0.      0.0772]
 [ 0.      0.      0.     ...  0.      0.     -0.3818]
 ...
 [ 0.      0.      0.     ...  0.      0.      0.3818]
 [ 0.      0.      0.     ...  0.      0.      0.5267]
 [ 0.      0.      0.     ...  0.      0.      0.6697]]


(1787, 5027)